const {chromium}=require('playwright'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const p=await b.newPage({viewport:{width:802,height:360},isMobile:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.argv[2]||'http://127.0.0.1:8876/index.html');await p.waitForFunction(()=>sprAllReady());
 const r=await p.evaluate(()=>{requestAnimationFrame=()=>0;AU.muted=true;G.noStory=true;startGame('yuki',null);const bad=[],rows=[],images=[];demoView.motion='auto';
 for(const hero of ['yuki','kage','mitsu','nobu','shin','musashi'])for(const type of Object.keys(BOSS_CHALLENGE))for(const mode of ['noStory','story','auto','attract']){const story=mode==='story';startStage(0,hero,mode==='attract');G.mode='play';G.noStory=!story;G.auto=mode==='auto';G.curCh=hero;G.waveOn=true;G.waves=[{x:999999,en:[]}];G.sq=[];G.player.x=440;G.player.inv=0;G.items=[];G.props=[];G.steeds=[];G.proj=[];G.parts=[];G.spcScene=null;G.ult=null;const e=spawnEn(type,1);if(story)endStory();const ally=mk('kage',320,570,0);ally.isPartner=true;G.partner=ally;G.fighters.push(ally);const q=addProj({k:'bullet',x:200,y:520,z:70,vx:6,team:1,life:900});const f=G.player;const snap=()=>JSON.stringify([f.x,f.y,f.hp,f.t,f.state,e.x,e.y,e.hp,e.t,e.inv,ally.x,ally.t,q.x,q.life,G.time,G.waveT,G.camx]);const before=snap();keys.KeyD=true;keys.KeyZ=true;let ticks=0;while(G.banner?.boss&&ticks<330){G.t++;stepGame();ticks++;}keys.KeyD=false;keys.KeyZ=false;const frozen=snap()===before;if(!frozen||ticks!==301)bad.push({hero,type,mode,ticks,frozen});rows.push({hero,type,mode,ticks,frozen});G.hitstop=0;for(let i=0;i<2;i++){G.t++;stepGame();}if(q.life===900||e.t===JSON.parse(before)[8])bad.push({hero,type,mode,noResume:true});}
 // Actual wave spawn must stop before the same frame updates any fighter.
 startStage(0,'yuki',false);G.noStory=true;G.mode='play';G.auto=false;G.demo=false;G.waveOn=true;G.waves=[{x:999999,en:[]}];G.waveT=49;G.sq=[{type:'boss1',d:50,side:1}];const f=G.player,x=f.x,t=f.t;keys.KeyD=true;updWorld();keys.KeyD=false;if(f.x!==x||f.t!==t)bad.push('spawn frame moved player');
 G.banner.t=80;G.flashT=0;G.shake=0;renderWorld();drawHUD();drawOverlays();images.push({name:'boss-cutin',png:cv.toDataURL().split(',')[1]});
 prepareWalkPreview();if(G.banner)bad.push('debug reset retained banner');return{bad,rows,images};});const dir='C:/Users/user/Desktop/output/sekigahara-new-20261006/qa/boss-cutin-freeze';fs.mkdirSync(dir,{recursive:true});for(const im of r.images){fs.writeFileSync(dir+'/'+im.name+'.png',Buffer.from(im.png,'base64'));delete im.png;}fs.writeFileSync(dir+'/tests.json',JSON.stringify({r,errors},null,2));console.log(JSON.stringify({cases:r.rows.length,badCount:r.bad.length,bad:r.bad.slice(0,4),errors}));if(r.bad.length||errors.length)process.exitCode=1;
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
