const {chromium}=require('playwright'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const p=await b.newPage({viewport:{width:802,height:360},isMobile:true,hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.argv[2]||'http://127.0.0.1:8876/index.html');await p.waitForFunction(()=>sprAllReady()&&Object.values(PIMG).every(imgOK)&&Object.values(STAND).every(imgOK));
 const r=await p.evaluate(()=>{requestAnimationFrame=()=>0;AU.muted=true;G.noStory=true;startGame('yuki',null);G.noStory=false;const bad=[],images=[],cases=[];
  for(const hero of ['yuki','kage','mitsu','nobu','shin','musashi'])for(const boss of Object.keys(BOSS_CHALLENGE)){G.curCh=hero;G.player=mk(hero,440,570,0);G.fighters=[G.player];G.proj=[];G.props=[];G.parts=[];G.boss=null;G.state='run';G.mode='play';const e=spawnEn(boss,1),x=G.player.x,hp=e.hp,time=G.time;if(G.mode!=='story'||G.story.right!==boss||G.story.L.length!==2)bad.push({hero,boss,missing:true});keys.KeyD=true;keys.KeyZ=true;for(let i=0;i<15;i++)frame();keys.KeyD=false;keys.KeyZ=false;if(G.player.x!==x||e.hp!==hp||G.time!==time)bad.push({hero,boss,simulationDuringStory:true});
   if(hero==='yuki'||boss==='boss3'){G.story.c=999;drawStory();images.push({name:hero+'-'+boss,png:cv.toDataURL().split(',')[1]});}endStory();if(G.mode!=='play'||G.boss!==e||e.hp!==hp)bad.push({hero,boss,resume:true});cases.push([hero,boss]);}
  G.auto=true;startBossStory(G.boss);for(let i=0;i<1500&&G.mode==='story';i++)stepStory();if(G.mode!=='play')bad.push('auto story did not finish');G.auto=false;startBossStory(G.boss);pressed.KeyS=true;stepStory();delete pressed.KeyS;if(G.mode!=='play')bad.push('skip failed');G.noStory=true;startBossStory(G.boss);if(G.mode!=='play')bad.push('noStory ignored');
  G.noStory=false;G.demo=true;startBossStory(G.boss);if(G.mode!=='play')bad.push('attract demo interrupted');return{bad,cases:cases.length,images};});
 const dir='C:/Users/user/Desktop/output/sekigahara-new-20261006/qa/boss-conversation';fs.mkdirSync(dir,{recursive:true});for(const im of r.images){fs.writeFileSync(dir+'/'+im.name+'.png',Buffer.from(im.png,'base64'));delete im.png;}fs.writeFileSync(dir+'/tests.json',JSON.stringify({r,errors},null,2));console.log(JSON.stringify({r,errors}));if(r.bad.length||errors.length)process.exitCode=1;
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
