const {chromium}=require('playwright'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_BIN||'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{
 const page=await b.newPage({viewport:{width:802,height:360},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.argv[2]||process.env.GAME_URL||'http://127.0.0.1:8876/index.html');await page.waitForFunction(()=>sprAllReady());
 const result=await page.evaluate(()=>{requestAnimationFrame=()=>0;AU.muted=true;G.lowq=true;startAuto('yuki',0);setInspectionMode(true);const bad=[],riders=[];
  for(const type of Object.keys(TY).filter(k=>TY[k].ai==='rider')){demoView.actor=type;demoView.motion='walk';prepareWalkPreview();const x=G.player.x;for(let t=0;t<20;t++)stepGame();riders.push({type,dx:G.player.x-x,phase:G.player.wp});if(G.player.x===x||G.player.wp===0)bad.push({type,frozen:true});}
  demoView.actor='boss2';demoView.motion='atk0';prepareWalkPreview();G.proj.push({k:'arrow',x:640,y:570,z:60,vx:6,vy:0,life:100,team:0,hit:new Set(),w:8});stepGame();const projectile=G.proj[0];if(!projectile||projectile.x!==646||projectile.life!==99)bad.push('projectile removed or not advanced');G.stuck.push({});G.marks.push({});prepareWalkPreview();if(G.stuck.length||G.marks.length||G.proj.length)bad.push('previous action effects survived reset');
  const victory=[];G.auto=false;G.demo=false;
  for(const type of ['yuki','kage','mitsu','nobu','shin','musashi'])for(const mounted of [false,true])for(const state of ['bossdown','clear']){G.player=mk(type,640,570,0);G.fighters=[G.player];setDemoMount(mounted);G.state=state;G.stateT=400;const p=G.player;p.state=mounted?'matk':'atk';p.cur=p.T.atk[0];p.kspin=20;p.chg=90;p.z=24;p.vz=3;const x=p.x,y=p.y,face=p.face;for(let i=0;i<80;i++)updPlayer(p,{r:true,d:true,atkP:true,atkH:true,jumpP:true,spcP:true,gd:true});if(p.x!==x||p.y!==y||p.face!==face||p.state!=='idle'||p.cur||p.kspin||p.chg||p.z)bad.push({type,mounted,state,moved:true});victory.push({type,mounted,state});}
  G.player=mk('musashi',640,570,0);G.fighters=[G.player];G.curCh='musashi';G.state='bossdown';G.stateT=450;G.victoryShift=0;renderWorld();drawHUD();return{bad,riders,victoryCases:victory.length,png:cv.toDataURL().split(',')[1]};});
 const out=(process.env.QA_OUT||'C:/Users/user/Desktop/output/sekigahara-new-20261006')+'/qa/single-debug-inspection';fs.mkdirSync(out,{recursive:true});fs.writeFileSync(out+'/victory-input-lock.png',Buffer.from(result.png,'base64'));delete result.png;fs.writeFileSync(out+'/regressions.json',JSON.stringify({result,errors},null,2));console.log(JSON.stringify({result,errors}));if(result.bad.length||errors.length)process.exitCode=1;
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
