// Inspect actual hit/emission updates and the whole rider frame drawn on that update.
const {chromium}=require('playwright'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_BIN||'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const p=await b.newPage({viewport:{width:802,height:360},isMobile:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.argv[2]||process.env.GAME_URL||'http://127.0.0.1:8876/index.html');await p.waitForFunction(()=>sprAllReady());const r=await p.evaluate(()=>{requestAnimationFrame=()=>0;AU.muted=true;G.noStory=true;startGame('musashi',null);G.auto=G.demo=false;G.camx=G.camMax=0;G.partner=null;Math.random=()=>0.5;const rows=[],bad=[],images=[];
 for(const hero of ['yuki','kage','mitsu','nobu','shin','musashi'])for(const weapon of [null,...Object.keys(WPN)])for(const special of [false,true])for(const face of [-1,1])for(const y of [YMIN,570,YMAX]){G.state='run';G.banner=G.cut=G.boss=G.spcScene=G.ult=null;G.proj=[];G.parts=[];G.props=[];G.items=[];G.steeds=[];G.hitN=G.flashT=G.hitstop=G.shake=0;const f=mk(hero,640,y,0),e=mk('sword',640+face*100,y,1);f.dm=1;f.face=face;f.inv=999;f.ki=300;f.mount={hp:6,max:6,col:MCOL[hero]};f.wpn=weapon?{k:weapon,uses:999}:null;e.hp=1000;e.entered=true;G.player=f;G.fighters=[f,e];updPlayer(f,special?{spcP:true}:{atkP:true});const impact=special?16:f.cur.hs;let hit=0,emit=0,contact=false,clips=0,shown=[],phases=new Set();
  for(let t=1;t<=(special?40:24);t++){G.t++;const hp=e.hp,n=G.proj.length;updPlayer(f,{});if(e.hp<hp)hit++;if(G.proj.length>n)emit++;const expectedFull=SPR['mountfull4_'+hero],full=expectedFull?.a[weapon||'default'],body=SPR['mountbody3_'+hero],expected=full?full[2]:body.a.all[3];shown=[];const old=ctx.drawImage;ctx.drawImage=function(im,...q){if(q.length===8&&(im===body.img||im===expectedFull?.img)){shown.push(q.slice(0,4));phases.add(q[0]+':'+q[1]);const m=ctx.getTransform(),x0=m.a*q[4]+m.e,x1=m.a*(q[4]+q[6])+m.e,y0=m.d*q[5]+m.f,y1=m.d*(q[5]+q[7])+m.f;if(Math.min(x0,x1)<0||Math.max(x0,x1)>W||y0<8||y1>H)clips++;if(t===impact&&q.slice(0,4).every((v,i)=>v===expected[i]))contact=true;}return old.call(this,im,...q);};ctx.setTransform(1,0,0,1,0,0);drawFighter(f);ctx.drawImage=old;
   if(!weapon&&face===1&&y===570&&[impact-1,impact,impact+1].includes(t)){G.shake=G.flashT=0;renderWorld();drawHUD();images.push({name:hero+'-'+(special?'special':'normal')+'-t'+t,png:cv.toDataURL().split(',')[1]});}
  }
  const ranged=!special&&['yumi','teppo'].includes(weapon),row={hero,weapon,special,face,y,impact,hit,emit,contact,clips,phases:phases.size};rows.push(row);if(!contact||clips||phases.size<3||(ranged?emit!==1||hit!==0:hit!==1||emit!==0))bad.push(row);
 }
 return{rows,bad,images};});const dir=(process.env.QA_OUT||'C:/Users/user/Desktop/output/sekigahara-new-20261006')+'/qa/mounted-contact-timing';fs.mkdirSync(dir,{recursive:true});for(const im of r.images){fs.writeFileSync(dir+'/'+im.name+'.png',Buffer.from(im.png,'base64'));delete im.png;}fs.writeFileSync(dir+'/tests.json',JSON.stringify({r,errors},null,2));console.log(JSON.stringify({cases:r.rows.length,badCount:r.bad.length,bad:r.bad.slice(0,5),errors}));if(r.bad.length||errors.length)process.exitCode=1;
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
