// Freeze spectators and hostile projectiles while the selected special keeps playing.
const {chromium}=require('playwright'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_BIN||'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{
 const p=await b.newPage({viewport:{width:802,height:360},isMobile:true});await p.goto(process.argv[2]||process.env.GAME_URL||'http://127.0.0.1:8876/index.html');await p.waitForFunction(()=>sprAllReady());
 const errors=[];p.on('pageerror',e=>errors.push(e.message));const r=await p.evaluate(()=>{requestAnimationFrame=()=>0;AU.muted=true;G.noStory=true;startGame('yuki',null);const bad=[],rows=[],upd=updEnemy;let enemyCalls=0;updEnemy=function(e){enemyCalls++;return upd(e);};
 for(const hero of ['yuki','kage','mitsu','nobu','shin','musashi'])for(const level of [1,2,3]){G.auto=false;G.demo=false;G.mode='play';G.state='run';G.camx=G.camMax=0;G.wi=0;G.waveOn=true;G.waves=[{x:0,en:[]}];G.sq=[];G.boss=null;G.items=[];G.props=[];G.parts=[];G.proj=[];G.steeds=[];G.hitstop=G.slow=0;G.ult=null;G.spcScene=null;G.cut=null;G.time=30000;const f=mk(hero,440,570,0),e=mk('sword',620,570,1),ally=mk('kage',320,570,0);e.entered=true;e.hp=e.maxhp=10000;ally.isPartner=true;f.ki=100*level;G.curCh=hero;G.player=f;G.partner=ally;G.fighters=[f,e,ally];const q=addProj({k:'bullet',x:200,y:520,z:70,vx:6,team:1,life:90});const before={ex:e.x,ey:e.y,et:e.t,ax:ally.x,ay:ally.y,at:ally.t,time:G.time};enemyCalls=0;startSpecial(f);let ticks=0;const rel=hero==='yuki'&&level<3;let snap=null;while(['spc','ult'].includes(f.state)&&ticks<400){if(rel&&f.state==='spc'&&f.rushEnd&&f.st===f.rushEnd&&!snap)snap={ex:e.x,ey:e.y,et:e.t,ax:ally.x,ay:ally.y,at:ally.t,time:G.time,calls:enemyCalls,ql:q.life,qx:q.x};G.t++;stepGame();ticks++;}
  // 幸村Lv1・Lv2は突進中だけ止め(槍に掛けた敵は運ぶので位置は変わる。敵の思考・味方・弾・時間は止まる)、最後の一突きで時間を戻す(吹き飛ぶ敵を見せるため)。突進が終わる時点までの停止を検査する
  if(rel){const ok=snap&&snap.ax===before.ax&&snap.at===before.at&&snap.qx===200&&snap.ql===90&&snap.time===before.time&&snap.calls===0&&enemyCalls>0;if(!ok||ticks>=400)bad.push({hero,level,rushFreeze:ok,snap,ticks});rows.push({hero,level,ticks,damage:10000-e.hp,frozenDuringRush:ok,releasedAtFinal:enemyCalls>0});continue;}
  const frozen=e.x===before.ex&&e.y===before.ey&&e.t===before.et&&ally.x===before.ax&&ally.y===before.ay&&ally.t===before.at&&q.x===200&&q.life===90&&G.time===before.time&&enemyCalls===0;
  if(!frozen||ticks>=400)bad.push({hero,level,frozen,ticks,enemyCalls,enemy:{x:e.x,y:e.y,t:e.t},ally:{x:ally.x,t:ally.t},foreign:{x:q.x,life:q.life},time:G.time});const damage=10000-e.hp;for(let i=0;i<30&&q.life===90;i++){G.t++;stepGame();}if(q.life===90)bad.push({hero,level,worldDidNotResume:true});rows.push({hero,level,ticks,damage,frozen});
 }
 const mounted=[];for(const hero of ['yuki','kage','mitsu','nobu','shin','musashi']){G.state='run';G.spcScene=null;G.ult=null;G.hitstop=0;G.player=mk(hero,440,570,0);G.fighters=[G.player];setDemoMount(true);const f=G.player,e=mk('sword',580,570,1);e.entered=true;e.hp=e.maxhp=10000;G.fighters.push(e);f.ki=100;const et=e.t,ex=e.x;updPlayer(f,{spcP:true});let ticks=0;while(f.state==='mspc'&&ticks<100){G.t++;stepGame();ticks++;}const ok=e.t===et&&e.x===ex&&e.hp<10000&&ticks>=40&&ticks<100&&!G.spcScene;if(!ok)bad.push({hero,mounted:true,ticks,et:e.t,ex:e.x,damage:10000-e.hp});mounted.push({hero,ticks,ok});}
 // Reset and interrupted casts must never leave the world locked.
 G.player=mk('mitsu',440,570,0);G.fighters=[G.player];G.player.ki=100;startSpecial(G.player);G.player.state='hurt';stepGame();if(G.spcScene)bad.push('interrupted special retained scene');
 G.player.ki=100;startSpecial(G.player);prepareWalkPreview();if(G.spcScene)bad.push('debug reset retained scene');
 G.player.ki=100;startSpecial(G.player);startStage(0,'yuki',false);if(G.spcScene||G.ult)bad.push('stage reset retained scene');
 updEnemy=upd;return{bad,rows,mounted};});const dir=(process.env.QA_OUT||'C:/Users/user/Desktop/output/sekigahara-new-20261006')+'/qa/special-world-freeze';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/tests.json',JSON.stringify(r,null,2));console.log(JSON.stringify({errors,mounted:r.mounted,cases:r.rows.length,bad:r.bad.slice(0,6),badCount:r.bad.length,rows:r.rows}));if(r.bad.length||errors.length)process.exitCode=1;
 // Render each caster in an actual Android-sized game scene.
 for(const hero of ['yuki','kage','mitsu','nobu','shin','musashi']){await p.evaluate(hero=>{G.auto=false;G.demo=false;G.state='run';G.spcScene=null;G.ult=null;G.hitstop=0;G.banner=null;G.vo=null;G.proj=[];G.parts=[];G.items=[];G.props=[];G.combo=0;G.hitPop=0;G.shake=0;G.flashT=0;G.player=mk(hero,440,570,0);G.player.ki=100;const e=mk('samurai',620,570,1);e.hp=10000;G.fighters=[G.player,e];startSpecial(G.player);for(let i=0;i<45;i++){G.t++;stepGame();}G.flashT=0;G.shake=0;renderWorld();drawHUD();drawOverlays();},hero);await p.screenshot({path:dir+'/'+hero+'.png'});}
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

