const {chromium}=require('playwright'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const p=await b.newPage({viewport:{width:802,height:360},isMobile:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.argv[2]||'http://127.0.0.1:8876/index.html');await p.waitForFunction(()=>sprAllReady());
 const r=await p.evaluate(()=>{requestAnimationFrame=()=>0;AU.muted=true;G.noStory=true;startGame('yuki',null);G.auto=G.demo=false;G.banner=null;G.camx=G.camMax=0;G.partner=null;const bad=[],rows=[],images=[],atlas=SPR.yukithrow1;if(!atlas?.ready)return{bad:['missing atlas'],rows,images};
 for(const type of ['sword','spear','samurai','gun','ninja','archer','bomber','brute','shield'])for(const face of [-1,1])for(const y of [YMIN,570,YMAX])for(const side of ['left','center','right']){G.state='run';G.boss=null;G.lastEn=null;G.hitN=0;G.comboT=0;G.hitPop=0;G.banner=null;G.ult=G.spcScene=null;G.hitstop=0;G.flashT=0;G.proj=[];G.parts=[];G.items=[];G.props=[];G.steeds=[];const f=mk('yuki',640,y,0);f.face=face;f.hp=f.maxhp=10000;f.inv=999;const edge=fighterScreenMargin(f);f.x=side==='left'?edge:side==='right'?W-edge:640;const e=mk(type,f.x+face*45,y,1);e.entered=true;e.hp=e.maxhp=1000;G.player=f;G.fighters=[f,e];startGrab(f,e);throwE(f,e,-face);if(!f.spearThrow||e.state!=='held'||f.face!==face)bad.push({type,face,y,side,start:true});let peak=0,released=false,landed=false,frames=new Set(),clips=[];
  for(let t=0;t<100;t++){G.t++;if(t<40)updPlayer(f,{});updEnemy(e);peak=Math.max(peak,e.z);if(f.spearThrow&&!f.spearThrow.released){const a=YUKI_THROW_TIPS[yukiThrowFrame(f)];if(e.heldBy!==f||Math.abs(e.x-f.x-face*a[0]*f.sc)>0.01||Math.abs(e.z-Math.max(0,-a[1]*f.sc-90*e.sc))>0.01)bad.push({type,face,y,side,t,attachment:true});frames.add(yukiThrowFrame(f));}if(e.thrown){if(!released&&e.vx*face>=0)bad.push({type,face,y,side,t,direction:true});released=true;if(e.z===0)landed=true;}
   // Inspect actual actor image rectangles, including the whole 256px throw cells.
   const old=ctx.drawImage;ctx.drawImage=function(img,...a){if(a.length===8){const m=ctx.getTransform(),x=a[4],yy=a[5],w=a[6],h=a[7],x0=m.a*x+m.c*yy+m.e,x1=m.a*(x+w)+m.c*(yy+h)+m.e,y0=m.b*x+m.d*yy+m.f,y1=m.b*(x+w)+m.d*(yy+h)+m.f;if(Math.min(x0,x1)<0||Math.max(x0,x1)>W||Math.min(y0,y1)<8||Math.max(y0,y1)>H)clips.push({t,x0,x1,y0,y1});}return old.call(this,img,...a);};ctx.setTransform(1,0,0,1,0,0);drawFighter(f);drawFighter(e);ctx.drawImage=old;
   if(type==='sword'&&face===1&&y===570&&side==='center'&&[4,9,14,19,24,29,34,39,54,69].includes(t)){G.flashT=0;G.shake=0;renderWorld();drawHUD();images.push({name:'t'+t,png:cv.toDataURL().split(',')[1]});}
  }
  if(clips.length)bad.push({type,face,y,side,clips:clips.slice(0,2),count:clips.length});if(!released||!landed||peak<80||f.state==='throw'||e.heldBy)bad.push({type,face,y,side,peak,released,landed,endState:f.state,held:!!e.heldBy});rows.push({type,face,y,side,peak,released,landed,frames:[...frames],damage:1000-e.hp});
 }
 // Legacy throws for all other heroes and Yukimura pickup weapons remain immediate.
 for(const hero of ['kage','mitsu','nobu','shin','musashi','yuki']){const f=mk(hero,640,570,0),e=mk('sword',690,570,1);e.hp=e.maxhp=1000;if(hero==='yuki')f.wpn={k:'odachi',uses:20};G.player=f;G.fighters=[f,e];startGrab(f,e);throwE(f,e,-1);if(f.spearThrow||e.heldBy||e.state!=='down'||e.vx>=0)bad.push({hero,legacy:true});}
 // Interrupts release a held enemy instead of leaving them floating forever.
 const f=mk('yuki',640,570,0),e=mk('sword',690,570,1);G.player=f;G.fighters=[f,e];startGrab(f,e);throwE(f,e,-1);for(let t=0;t<12;t++){updPlayer(f,{});updEnemy(e);}f.state='hurt';f.hurtT=20;updPlayer(f,{});updEnemy(e);if(e.heldBy||f.spearThrow||e.state!=='down')bad.push({interruption:true});
 // Ground enemies are hit once on the descending landing path, not in the high lift.
 
 for(const face of [-1,1]){const f=mk('yuki',640,570,0),e=mk('sword',640+face*45,570,1);f.face=face;G.player=f;G.fighters=[f,e];startGrab(f,e);updPlayer(f,{atkP:true,l:face===1,r:face===-1});if(!f.spearThrow||f.face!==face)bad.push({face,inputThrow:true});knock(e,1,3,6);updPlayer(f,{});if(f.spearThrow||e.heldBy||f.state!=='idle'||e.state!=='down')bad.push({face,victimInterruption:true});}
 const collateral=[];for(const face of [-1,1]){const f=mk('yuki',640,570,0),e=mk('sword',640+face*45,570,1),o=mk('sword',640-face*350,570,1);f.face=face;f.inv=999;e.hp=o.hp=1000;e.entered=o.entered=true;const near=mk('sword',640-face*110,570,1);near.hp=1000;G.player=f;G.fighters=[f,e,o,near];startGrab(f,e);throwE(f,e,-face);let first=-1,hp=1000;for(let t=0;t<110;t++){G.t++;if(t<40)updPlayer(f,{});updEnemy(e);if(o.hp<1000&&first<0){first=t;hp=o.hp;}if(first>=0&&o.hp!==hp)bad.push({face,collateralRepeated:true});}if(first<25)bad.push({face,landingHitMissing:first});if(near.hp!==1000)bad.push({face,highAirHitGroundEnemy:true});collateral.push({face,first,hp});}
 // A fatal throw keeps the victim's whole body attached until release.
 {const f=mk('yuki',640,570,0),e=mk('sword',685,570,1);f.inv=999;e.hp=1;G.player=f;G.fighters=[f,e];startGrab(f,e);throwE(f,e,-1);for(let t=0;t<40;t++){updPlayer(f,{});updEnemy(e);}if(e.hp!==0||!e.dying||e.heldBy||e.decap)bad.push({fatal:true});}
 return{bad,rows,images,collateral};});const dir='C:/Users/user/Desktop/output/sekigahara-new-20261006/qa/yuki-spear-throw-v1/runtime';fs.mkdirSync(dir,{recursive:true});for(const im of r.images){fs.writeFileSync(dir+'/'+im.name+'.png',Buffer.from(im.png,'base64'));delete im.png;}fs.writeFileSync(dir+'/tests.json',JSON.stringify({r,errors},null,2));console.log(JSON.stringify({cases:r.rows.length,badCount:r.bad.length,bad:r.bad.slice(0,8),errors}));if(r.bad.length||errors.length)process.exitCode=1;
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
