// Long spear artwork must meet the victim when damage starts, without clipped cells.
const {chromium}=require('playwright'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_BIN||'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const p=await b.newPage({viewport:{width:802,height:360},isMobile:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.argv[2]||process.env.GAME_URL||'http://127.0.0.1:8876/index.html');await p.waitForFunction(()=>sprAllReady());
 const r=await p.evaluate(()=>{requestAnimationFrame=()=>0;AU.muted=true;G.noStory=true;startGame('yuki',null);G.auto=G.demo=false;G.camx=G.camMax=0;G.partner=null;Math.random=()=>0.5;const rows=[],bad=[],images=[];
 for(const idx of [0,1])for(const face of [-1,1])for(const y of [YMIN,570,YMAX])for(const side of ['left','center','right'])for(const dist of [190,270]){G.state='run';G.banner=G.cut=G.boss=G.ult=G.spcScene=null;G.hitstop=G.shake=G.flashT=G.hitN=0;G.proj=[];G.parts=[];G.items=[];G.props=[];G.steeds=[];const f=mk('yuki',640,y,0);f.face=face;f.inv=999;f.dm=1;const edge=fighterScreenMargin(f);f.x=side==='center'?640:side==='left'?edge:W-edge;const e=mk('sword',f.x+face*dist,y,1);e.hp=1000;e.entered=true;G.player=f;G.fighters=[f,e];startPAtk(f,idx);let first=-1,calls=0,tip=0,phase=-1,clips=0;
  for(let t=0;t<16;t++){G.t++;const hp=e.hp;updPlayer(f,{});if(e.hp<hp){calls++;if(first<0)first=f.st;}
   const old=ctx.drawImage;ctx.drawImage=function(im,...q){if(q.length===8&&im===SPR.yukiattack2.img){const m=ctx.getTransform(),x0=m.a*q[4]+m.e,x1=m.a*(q[4]+q[6])+m.e,y0=m.d*q[5]+m.f,y1=m.d*(q[5]+q[7])+m.f;if(Math.min(x0,x1)<0||Math.max(x0,x1)>W||y0<8||y1>H)clips++;if(f.st===5){phase=q[0]/256;const localTip=idx===0?211:238;tip=(m.a*((localTip-86.43401240035429)*1.326362781954887)+m.e-f.x)*face;}}return old.call(this,im,...q);};ctx.setTransform(1,0,0,1,0,0);drawFighter(f);ctx.drawImage=old;
   if(face===1&&y===570&&side==='center'&&dist===190&&[2,5,9,13].includes(f.st)){G.flashT=G.shake=0;renderWorld();drawHUD();images.push({name:'a'+(idx+1)+'-t'+f.st,png:cv.toDataURL().split(',')[1]});}
  }
  const row={idx,face,y,side,dist,first,calls,phase,tip,clips,damage:1000-e.hp};rows.push(row);if(clips||phase!==2||tip<TY.yuki.atk[idx].rng-12||tip>TY.yuki.atk[idx].rng+30|| (dist===190?(first!==5||calls!==1||1000-e.hp!==TY.yuki.atk[idx].dmg):calls!==0))bad.push(row);
 }
 // Pickup attacks retain their weapon definitions and never draw the primary spear.
 for(const weapon of Object.keys(WPN)){const f=mk('yuki',640,570,0);f.wpn={k:weapon,uses:99};G.player=f;G.fighters=[f];startPAtk(f,0);f.st=f.cur.hs||5;let used=false;const old=ctx.drawImage;ctx.drawImage=function(im,...q){if(im===SPR.yukiattack2.img)used=true;return old.call(this,im,...q);};drawFighter(f);ctx.drawImage=old;if(used)bad.push({weapon,primarySpearUsed:true});}
 return{rows,bad,images};});const dir=(process.env.QA_OUT||'C:/Users/user/Desktop/output/sekigahara-new-20261006')+'/qa/yuki-normal-reach-v2/runtime';fs.mkdirSync(dir,{recursive:true});for(const im of r.images){fs.writeFileSync(dir+'/'+im.name+'.png',Buffer.from(im.png,'base64'));delete im.png;}fs.writeFileSync(dir+'/tests.json',JSON.stringify({r,errors},null,2));console.log(JSON.stringify({cases:r.rows.length,badCount:r.bad.length,bad:r.bad.slice(0,8),errors}));if(r.bad.length||errors.length)process.exitCode=1;
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
